development:
  adapter: postgresql
  encoding: utf8
  database: atlasnomad_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: atlasnomad_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: atlasnomad_production
  pool: 5
