# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

require 'mechanize'

mechanize = Mechanize.new

url_array = [
"http://travel.state.gov/content/passports/english/country/bangladesh.html",
"http://travel.state.gov/content/passports/english/country/belgium.html",
"http://travel.state.gov/content/passports/english/country/burkina-faso.html",
"http://travel.state.gov/content/passports/english/country/bulgaria.html",
"http://travel.state.gov/content/passports/english/country/bosnia-herzegovina.html",
"http://travel.state.gov/content/passports/english/country/brunei.html",
"http://travel.state.gov/content/passports/english/country/bolivia.html",
"http://travel.state.gov/content/passports/english/country/japan.html",
"http://travel.state.gov/content/passports/english/country/burundi.html",
"http://travel.state.gov/content/passports/english/country/benin.html",
"http://travel.state.gov/content/passports/english/country/bhutan.html",
"http://travel.state.gov/content/passports/english/country/jamaica.html",
"http://travel.state.gov/content/passports/english/country/botswana.html",
"http://travel.state.gov/content/passports/english/country/brazil.html",
"http://travel.state.gov/content/passports/english/country/the-bahamas.html",
"http://travel.state.gov/content/passports/english/country/belarus.html",
"http://travel.state.gov/content/passports/english/country/belize.html",
"http://travel.state.gov/content/passports/english/country/russia.html",
"http://travel.state.gov/content/passports/english/country/rwanda.html",
"http://travel.state.gov/content/passports/english/country/serbia.html",
"http://travel.state.gov/content/passports/english/country/lithuania.html",
"http://travel.state.gov/content/passports/english/country/luxembourg.html",
"http://travel.state.gov/content/passports/english/country/liberia.html",
"http://travel.state.gov/content/passports/english/country/romania.html",
"http://travel.state.gov/content/passports/english/country/guinea-bissau.html",
"http://travel.state.gov/content/passports/english/country/guatemala.html",
"http://travel.state.gov/content/passports/english/country/greece.html",
"http://travel.state.gov/content/passports/english/country/guinea.html",
"http://travel.state.gov/content/passports/english/country/guyana.html",
"http://travel.state.gov/content/passports/english/country/georgia.html",
"http://travel.state.gov/content/passports/english/country/united-kingdom.html",
"http://travel.state.gov/content/passports/english/country/gabon.html",
"http://travel.state.gov/content/passports/english/country/guinea.html",
"http://travel.state.gov/content/passports/english/country/the-gambia.html",
"http://travel.state.gov/content/passports/english/country/denmark.html",
"http://travel.state.gov/content/passports/english/country/kuwait.html",
"http://travel.state.gov/content/passports/english/country/ghana.html",
"http://travel.state.gov/content/passports/english/country/oman.html",
"http://travel.state.gov/content/passports/english/country/somalia.html",
"http://travel.state.gov/content/passports/english/country/kosovo.html",
"http://travel.state.gov/content/passports/english/country/jordan.html",
"http://travel.state.gov/content/passports/english/country/croatia.html",
"http://travel.state.gov/content/passports/english/country/haiti.html",
"http://travel.state.gov/content/passports/english/country/hungary.html",
"http://travel.state.gov/content/passports/english/country/honduras.html",
"http://travel.state.gov/content/passports/english/country/puerto-rico.html",
"http://travel.state.gov/content/passports/english/country/palestine.html",
"http://travel.state.gov/content/passports/english/country/Portugal.html",
"http://travel.state.gov/content/passports/english/country/paraguay.html",
"http://travel.state.gov/content/passports/english/country/panama.html",
"http://travel.state.gov/content/passports/english/country/papua-new-guinea.html",
"http://travel.state.gov/content/passports/english/country/peru.html",
"http://travel.state.gov/content/passports/english/country/pakistan.html",
"http://travel.state.gov/content/passports/english/country/philippines.html",
"http://travel.state.gov/content/passports/english/country/poland.html",
"http://travel.state.gov/content/passports/english/country/cyprus.html",
"http://travel.state.gov/content/passports/english/country/zambia.html",
"http://travel.state.gov/content/passports/english/country/w.-sahara.html",
"http://travel.state.gov/content/passports/english/country/estonia.html",
"http://travel.state.gov/content/passports/english/country/egypt.html",
"http://travel.state.gov/content/passports/english/country/south-africa.html",
"http://travel.state.gov/content/passports/english/country/ecuador.html",
"http://travel.state.gov/content/passports/english/country/albania.html",
"http://travel.state.gov/content/passports/english/country/angola.html",
"http://travel.state.gov/content/passports/english/country/kazakhstan.html",
"http://travel.state.gov/content/passports/english/country/ethiopia.html",
"http://travel.state.gov/content/passports/english/country/zimbabwe.html",
"http://travel.state.gov/content/passports/english/country/spain.html",
"http://travel.state.gov/content/passports/english/country/eritrea.html",
"http://travel.state.gov/content/passports/english/country/montenegro.html",
"http://travel.state.gov/content/passports/english/country/moldova.html",
"http://travel.state.gov/content/passports/english/country/madagascar.html",
"http://travel.state.gov/content/passports/english/country/morocco.html",
"http://travel.state.gov/content/passports/english/country/uzbekistan.html",
"http://travel.state.gov/content/passports/english/country/burma.html",
"http://travel.state.gov/content/passports/english/country/mali.html",
"http://travel.state.gov/content/passports/english/country/mongolia.html",
"http://travel.state.gov/content/passports/english/country/macedonia.html",
"http://travel.state.gov/content/passports/english/country/malawi.html",
"http://travel.state.gov/content/passports/english/country/mauritania.html",
"http://travel.state.gov/content/passports/english/country/uganda.html",
"http://travel.state.gov/content/passports/english/country/malaysia.html",
"http://travel.state.gov/content/passports/english/country/mexico.html",
"http://travel.state.gov/content/passports/english/country/vanuatu.html",
"http://travel.state.gov/content/passports/english/country/france.html",
"http://travel.state.gov/content/passports/english/country/finland.html",
"http://travel.state.gov/content/passports/english/country/fiji.html",
"http://travel.state.gov/content/passports/english/country/united-kingdom.html",
"http://travel.state.gov/content/passports/english/country/nicaragua.html",
"http://travel.state.gov/content/passports/english/country/netherlands.html",
"http://travel.state.gov/content/passports/english/country/norway.html",
"http://travel.state.gov/content/passports/english/country/namibia.html",
"http://travel.state.gov/content/passports/english/country/new-caledonia.html",
"http://travel.state.gov/content/passports/english/country/niger.html",
"http://travel.state.gov/content/passports/english/country/nigeria.html",
"http://travel.state.gov/content/passports/english/country/new-zealand.html",
"http://travel.state.gov/content/passports/english/country/nepal.html",
"http://travel.state.gov/content/passports/english/country/cote-divoire.html",
"http://travel.state.gov/content/passports/english/country/switzerland-and-liechtenstein.html",
"http://travel.state.gov/content/passports/english/country/colombia.html",
"http://travel.state.gov/content/passports/english/country/china.html",
"http://travel.state.gov/content/passports/english/country/cameroon.html",
"http://travel.state.gov/content/passports/english/country/chile.html",
"http://travel.state.gov/content/passports/english/country/canada.html",
"http://travel.state.gov/content/passports/english/country/congo-kinshasa.html",
"http://travel.state.gov/content/passports/english/country/central-african-republic.html",
"http://travel.state.gov/content/passports/english/country/congo-kinshasa.html",
"http://travel.state.gov/content/passports/english/country/czech-republic.html",
"http://travel.state.gov/content/passports/english/country/cyprus.html",
"http://travel.state.gov/content/passports/english/country/costa-rica.html",
"http://travel.state.gov/content/passports/english/country/cuba.html",
"http://travel.state.gov/content/passports/english/country/swaziland.html",
"http://travel.state.gov/content/passports/english/country/syria.html",
"http://travel.state.gov/content/passports/english/country/kyrgyzstan.html",
"http://travel.state.gov/content/passports/english/country/kenya.html",
"http://travel.state.gov/content/passports/english/country/sudan.html",
"http://travel.state.gov/content/passports/english/country/suriname.html",
"http://travel.state.gov/content/passports/english/country/cambodia.html",
"http://travel.state.gov/content/passports/english/country/el-salvador.html",
"http://travel.state.gov/content/passports/english/country/slovakia.html",
"http://travel.state.gov/content/passports/english/country/korea-south.html",
"http://travel.state.gov/content/passports/english/country/slovenia.html",
"http://travel.state.gov/content/passports/english/country/korea-north.html",
"http://travel.state.gov/content/passports/english/country/somalia.html",
"http://travel.state.gov/content/passports/english/country/senegal.html",
"http://travel.state.gov/content/passports/english/country/sierra-leone.html",
"http://travel.state.gov/content/passports/english/country/solomon-islands..html",
"http://travel.state.gov/content/passports/english/country/saudi-arabia.html",
"http://travel.state.gov/content/passports/english/country/sweden.html",
"http://travel.state.gov/content/passports/english/country/sudan.html",
"http://travel.state.gov/content/passports/english/country/dominican-republic.html",
"http://travel.state.gov/content/passports/english/country/djibouti.html",
"http://travel.state.gov/content/passports/english/country/denmark.html",
"http://travel.state.gov/content/passports/english/country/germany.html",
"http://travel.state.gov/content/passports/english/country/yemen.html",
"http://travel.state.gov/content/passports/english/country/austria.html",
"http://travel.state.gov/content/passports/english/country/algeria.html",
"http://travel.state.gov/content/passports/english/country/united-states.html",
"http://travel.state.gov/content/passports/english/country/latvia.html",
"http://travel.state.gov/content/passports/english/country/uruguay.html",
"http://travel.state.gov/content/passports/english/country/lebanon.html",
"http://travel.state.gov/content/passports/english/country/laos.html",
"http://travel.state.gov/content/passports/english/country/taiwan.html",
"http://travel.state.gov/content/passports/english/country/trinidad-tobago.html",
"http://travel.state.gov/content/passports/english/country/turkey.html",
"http://travel.state.gov/content/passports/english/country/sri-lanka.html",
"http://travel.state.gov/content/passports/english/country/tunisia.html",
"http://travel.state.gov/content/passports/english/country/timor-leste.html",
"http://travel.state.gov/content/passports/english/country/turkmenistan.html",
"http://travel.state.gov/content/passports/english/country/tajikistan.html",
"http://travel.state.gov/content/passports/english/country/lesotho.html",
"http://travel.state.gov/content/passports/english/country/thailand.html",
"http://travel.state.gov/content/passports/english/country/antarctica.html",
"http://travel.state.gov/content/passports/english/country/togo.html",
"http://travel.state.gov/content/passports/english/country/chad.html",
"http://travel.state.gov/content/passports/english/country/libya.html",
"http://travel.state.gov/content/passports/english/country/united-arab-emirates.html",
"http://travel.state.gov/content/passports/english/country/venezuela.html",
"http://travel.state.gov/content/passports/english/country/afghanistan.html",
"http://travel.state.gov/content/passports/english/country/iraq.html",
"http://travel.state.gov/content/passports/english/country/iceland.html",
"http://travel.state.gov/content/passports/english/country/iran.html",
"http://travel.state.gov/content/passports/english/country/armenia.html",
"http://travel.state.gov/content/passports/english/country/italy.html",
"http://travel.state.gov/content/passports/english/country/vietnam.html",
"http://travel.state.gov/content/passports/english/country/argentina.html",
"http://travel.state.gov/content/passports/english/country/australia.html",
"http://travel.state.gov/content/passports/english/country/israel.html",
"http://travel.state.gov/content/passports/english/country/india.html",
"http://travel.state.gov/content/passports/english/country/tanzania.html",
"http://travel.state.gov/content/passports/english/country/azerbaijan.html",
"http://travel.state.gov/content/passports/english/country/ireland.html",
"http://travel.state.gov/content/passports/english/country/indonesia.html",
"http://travel.state.gov/content/passports/english/country/ukraine.html",
"http://travel.state.gov/content/passports/english/country/qatar.html",
"http://travel.state.gov/content/passports/english/country/mozambique.html"]

country_codes = [
"BD",
"BE",
"BF",
"BG",
"BA",
"BN",
"BO",
"JP",
"BI",
"BJ",
"BT",
"JM",
"BW",
"BR",
"BS",
"BY",
"BZ",
"RU",
"RW",
"RS",
"LT",
"LU",
"LR",
"RO",
"GW",
"GT",
"GR",
"GQ",
"GY",
"GE",
"GB",
"GA",
"GN",
"GM",
"GL",
"KW",
"GH",
"OM",
"_1",
"_0",
"JO",
"HR",
"HT",
"HU",
"HN",
"PR",
"PS",
"PT",
"PY",
"PA",
"PG",
"PE",
"PK",
"PH",
"PL",
"-99",
"ZM",
"EH",
"EE",
"EG",
"ZA",
"EC",
"AL",
"AO",
"KZ",
"ET",
"ZW",
"ES",
"ER",
"ME",
"MD",
"MG",
"MA",
"UZ",
"MM",
"ML",
"MN",
"MK",
"MW",
"MR",
"UG",
"MY",
"MX",
"VU",
"FR",
"FI",
"FJ",
"FK",
"NI",
"NL",
"NO",
"NA",
"NC",
"NE",
"NG",
"NZ",
"NP",
"CI",
"CH",
"CO",
"CN",
"CM",
"CL",
"CA",
"CG",
"CF",
"CD",
"CZ",
"CY",
"CR",
"CU",
"SZ",
"SY",
"KG",
"KE",
"SS",
"SR",
"KH",
"SV",
"SK",
"KR",
"SI",
"KP",
"SO",
"SN",
"SL",
"SB",
"SA",
"SE",
"SD",
"DO",
"DJ",
"DK",
"DE",
"YE",
"AT",
"DZ",
"US",
"LV",
"UY",
"LB",
"LA",
"TW",
"TT",
"TR",
"LK",
"TN",
"TL",
"TM",
"TJ",
"LS",
"TH",
"TF",
"TG",
"TD",
"LY",
"AE",
"VE",
"AF",
"IQ",
"IS",
"IR",
"AM",
"IT",
"VN",
"AR",
"AU",
"IL",
"IN",
"TZ",
"AZ",
"IE",
"ID",
"UA",
"QA",
"MZ"
]
i = 0
url_array.each do |url|
	page = mechanize.get(url)

	flag = "http://travel.state.gov" + page.at('.flag').attributes['src'].value

	Country.create(
		name: page.at('h1').text.strip, 
		official_name: page.at('.official_name').text.strip,
		code: country_codes[i],
		flag: flag,
		passport_validity: page.at('.quick_fact1 > p').text.strip,
		passport_pages: page.at('.quick_fact2 > p').text.strip,
		tourist_visa: page.at('.quick_fact3 > p').text.strip,
		vaccinations: page.at('.quick_fact4 > p').text.strip,
		entry_currency: page.at('.quick_fact5 > p').text.strip,
		exit_currency: page.at('.quick_fact6 > p').text.strip
	)
	i += 1
end

Country.create(
	name: "Puerto Rico"
	official_name: "Puerto Rico",
	code: "PR",
	flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Puerto_Rico.svg/2000px-Flag_of_Puerto_Rico.svg.png",
	passport_validity: "Same as U.S.",
	passport_pages: "Same as U.S.",
	tourist_visa: "Same as U.S.",
	vaccinations: "Same as U.S.",
	entry_currency: "Same as U.S.",
	exit_currency: "Same as U.S."
)

Country.create(
	name: "Palestine"
	official_name: "Palestine",
	code: "PS",
	flag: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Palestine_flag.jpg",
	passport_validity: "Same as Isral (Not a joke)",
	passport_pages: "Same as Isral (Not a joke)",
	tourist_visa: "Same as Isral (Not a joke)",
	vaccinations: "Same as Isral (Not a joke)",
	entry_currency: "Same as Isral (Not a joke)",
	exit_currency: "Same as Isral (Not a joke)"
)

Country.create(
	name: "West Sahara"
	official_name: "West Sahara",
	code: "EH",
	flag: "http://www.mapsofworld.com/flags/images/world-flags/western-sahara-flag.jpg",
	passport_validity: "Not recommeneded for travel",
	passport_pages: "Not recommeneded for travel",
	tourist_visa: "Not recommeneded for travel",
	vaccinations: "Not recommeneded for travel",
	entry_currency: "Not recommeneded for travel",
	exit_currency: "Not recommeneded for travel"
)

Country.create(
	name: "United States"
	official_name: "The United States of America",
	code: "US",
	flag: "http://khongthe.com/wallpapers/abstract/america-the-beautiful-230904.jpg",
	passport_validity: "Whatever you want because freedom",
	passport_pages: "Whatever you want because freedom",
	tourist_visa: "Whatever you want because freedom",
	vaccinations: "Whatever you want because freedom",
	entry_currency: "Whatever you want because freedom",
	exit_currency: "Whatever you want because freedom"
)

Country.create(
	name: "Israel"
	official_name: "Israel",
	code: "IL",
	flag: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg",
	passport_validity: "Six months",
	passport_pages: "One page required for entry stamp",
	tourist_visa: "Yes, but you can obtain at the port of entry",
	vaccinations: "Polio vaccination up to 1 year before travel is recommended.",
	entry_currency: "None",
	exit_currency: "None" 
)

######################################
## WARNINGS ##
######################################

warning_page = mechanize.get("http://travel.state.gov/content/passports/english/alertswarnings.html")

table = warning_page.at('table > tbody')

trs = table.css('tr')
links = trs.css('a')

array = []

trs.each do |tr|
	tr.css('td').each do |line|
		array << line.text.strip
	end
end

warning_array = array.each_slice(3).to_a
i = 0
warning_array.each do |warning|
	warning << links[i].attributes["href"].value
	i += 1
end

warning_array.each do |warning|
	search = warning[2].gsub(" Travel Warning", "") if warning[0] == "Warning"
	country = Country.where(name: search).first
	country == nil ? country = 0 : country = country.id
	Warning.create(
		country_id: country,
		warning_type: warning[0],
		date: warning[1],
		location: warning[2],
		warning_link: "http://travel.state.gov#{warning[3]}"
		)
	p Warning.last.id
end

