# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

require 'mechanize'

mechanize = Mechanize.new

countries = 
{"BD"=>"bangladesh",
 "BE"=>"belgium",
 "BF"=>"burkina-faso",
 "BG"=>"bulgaria",
 "BA"=>"bosnia-herzegovina",
 "BN"=>"brunei",
 "BO"=>"bolivia",
 "JP"=>"japan",
 "BI"=>"burundi",
 "BJ"=>"benin",
 "BT"=>"bhutan",
 "JM"=>"jamaica",
 "BW"=>"botswana",
 "BR"=>"brazil",
 "BS"=>"the-bahamas",
 "BY"=>"belarus",
 "BZ"=>"belize",
 "RU"=>"russia",
 "RW"=>"rwanda",
 "RS"=>"serbia",
 "LT"=>"lithuania",
 "LU"=>"luxembourg",
 "LR"=>"liberia",
 "RO"=>"romania",
 "GW"=>"guinea-bissau",
 "GT"=>"guatemala",
 "GR"=>"greece",
 "GQ"=>"equitorial-guinea",
 "GY"=>"guyana",
 "GE"=>"georgia",
 "GB"=>"united-kingdom",
 "GA"=>"gabon",
 "GN"=>"guinea",
 "GM"=>"the-gambia",
 "GL"=>"denmark",
 "KW"=>"kuwait",
 "GH"=>"ghana",
 "OM"=>"oman",
 "_1"=>"somalia",
 "_0"=>"kosovo",
 "JO"=>"jordan",
 "HR"=>"croatia",
 "HT"=>"haiti",
 "HU"=>"hungary",
 "HN"=>"honduras",
 # "PR"=>"puerto-rico",
 # "PS"=>"palestine",
 "PT"=>"Portugal",
 "PY"=>"paraguay",
 "PA"=>"panama",
 "PG"=>"papua-new-guinea",
 "PE"=>"peru",
 "PK"=>"pakistan",
 "PH"=>"philippines",
 "PL"=>"poland",
 "-99"=>"cyprus",
 "ZM"=>"zambia",
 # "EH"=>"w.-sahara",
 "EE"=>"estonia",
 "EG"=>"egypt",
 "ZA"=>"south-africa",
 "EC"=>"ecuador",
 "AL"=>"albania",
 "AO"=>"angola",
 "KZ"=>"kazakhstan",
 "ET"=>"ethiopia",
 "ZW"=>"zimbabwe",
 "ES"=>"spain",
 "ER"=>"eritrea",
 "ME"=>"montenegro",
 "MD"=>"moldova",
 "MG"=>"madagascar",
 "MA"=>"morocco",
 "UZ"=>"uzbekistan",
 "MM"=>"burma",
 "ML"=>"mali",
 "MN"=>"mongolia",
 "MK"=>"macedonia",
 "MW"=>"malawi",
 "MR"=>"mauritania",
 "UG"=>"uganda",
 "MY"=>"malaysia",
 "MX"=>"mexico",
 "VU"=>"vanuatu",
 "FR"=>"france",
 "FI"=>"finland",
 "FJ"=>"fiji",
 "FK"=>"united-kingdom",
 "NI"=>"nicaragua",
 "NL"=>"netherlands",
 "NO"=>"norway",
 "NA"=>"namibia",
 "NC"=>"new-caledonia",
 "NE"=>"niger",
 "NG"=>"nigeria",
 "NZ"=>"new-zealand",
 "NP"=>"nepal",
 "CI"=>"cote-divoire",
 "CH"=>"switzerland-and-liechtenstein",
 "CO"=>"colombia",
 "CN"=>"china",
 "CM"=>"cameroon",
 "CL"=>"chile",
 "CA"=>"canada",
 "CG"=>"congo-kinshasa",
 "CF"=>"central-african-republic",
 "CD"=>"congo-kinshasa",
 "CZ"=>"czech-republic",
 "CY"=>"cyprus",
 "CR"=>"costa-rica",
 "CU"=>"cuba",
 "SZ"=>"swaziland",
 "SY"=>"syria",
 "KG"=>"kyrgyzstan",
 "KE"=>"kenya",
 "SS"=>"sudan",
 "SR"=>"suriname",
 "KH"=>"cambodia",
 "SV"=>"el-salvador",
 "SK"=>"slovakia",
 "KR"=>"korea-south",
 "SI"=>"slovenia",
 "KP"=>"korea-north",
 "SO"=>"somalia",
 "SN"=>"senegal",
 "SL"=>"sierra-leone",
 "SB"=>"solomon-islands.",
 "SA"=>"saudi-arabia",
 "SE"=>"sweden",
 "SD"=>"sudan",
 "DO"=>"dominican-republic",
 "DJ"=>"djibouti",
 "DK"=>"denmark",
 "DE"=>"germany",
 "YE"=>"yemen",
 "AT"=>"austria",
 "DZ"=>"algeria",
 # "US"=>"united-states",
 "LV"=>"latvia",
 "UY"=>"uruguay",
 "LB"=>"lebanon",
 "LA"=>"laos",
 "TW"=>"taiwan",
 "TT"=>"trinidad-tobago",
 "TR"=>"turkey",
 "LK"=>"sri-lanka",
 "TN"=>"tunisia",
 "TL"=>"timor-leste",
 "TM"=>"turkmenistan",
 "TJ"=>"tajikistan",
 "LS"=>"lesotho",
 "TH"=>"thailand",
 "TF"=>"antarctica",
 "TG"=>"togo",
 "TD"=>"chad",
 "LY"=>"libya",
 "AE"=>"united-arab-emirates",
 "VE"=>"venezuela",
 "AF"=>"afghanistan",
 "IQ"=>"iraq",
 "IS"=>"iceland",
 "IR"=>"iran",
 "AM"=>"armenia",
 "IT"=>"italy",
 "VN"=>"vietnam",
 "AR"=>"argentina",
 "AU"=>"australia",
 # "IL"=>"israel",
 "IN"=>"india",
 "TZ"=>"tanzania",
 "AZ"=>"azerbaijan",
 "IE"=>"ireland",
 "ID"=>"indonesia",
 "UA"=>"ukraine",
 "QA"=>"qatar",
 "MZ"=>"mozambique"}
countries.values.each do |country|
	page = mechanize.get("http://travel.state.gov/content/passports/english/country/#{country}.html")
	p country
	flag = "http://travel.state.gov" + page.at('.flag').attributes['src'].value

	Country.create(
		name: page.at('h1').text.strip, 
		official_name: page.at('.official_name').text.strip,
		code: countries.key(country),
		flag: flag,
		passport_validity: page.at('.quick_fact1 > p').text.strip,
		passport_pages: page.at('.quick_fact2 > p').text.strip,
		tourist_visa: page.at('.quick_fact3 > p').text.strip,
		vaccinations: page.at('.quick_fact4 > p').text.strip,
		entry_currency: page.at('.quick_fact5 > p').text.strip,
		exit_currency: page.at('.quick_fact6 > p').text.strip
	)
end

Country.create(
	name: "Puerto Rico",
	official_name: "Puerto Rico",
	code: "PR",
	flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Puerto_Rico.svg/2000px-Flag_of_Puerto_Rico.svg.png",
	passport_validity: "Same as U.S.",
	passport_pages: "Same as U.S.",
	tourist_visa: "Same as U.S.",
	vaccinations: "Same as U.S.",
	entry_currency: "Same as U.S.",
	exit_currency: "Same as U.S."
)

Country.create(
	name: "Palestine",
	official_name: "Palestine",
	code: "PS",
	flag: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Palestine_flag.jpg",
	passport_validity: "Same as Isral (Not a joke)",
	passport_pages: "Same as Isral (Not a joke)",
	tourist_visa: "Same as Isral (Not a joke)",
	vaccinations: "Same as Isral (Not a joke)",
	entry_currency: "Same as Isral (Not a joke)",
	exit_currency: "Same as Isral (Not a joke)"
)

Country.create(
	name: "West Sahara",
	official_name: "West Sahara",
	code: "EH",
	flag: "http://www.mapsofworld.com/flags/images/world-flags/western-sahara-flag.jpg",
	passport_validity: "Not recommeneded for travel",
	passport_pages: "Not recommeneded for travel",
	tourist_visa: "Not recommeneded for travel",
	vaccinations: "Not recommeneded for travel",
	entry_currency: "Not recommeneded for travel",
	exit_currency: "Not recommeneded for travel"
)

Country.create(
	name: "United States",
	official_name: "The United States of America",
	code: "US",
	flag: "http://khongthe.com/wallpapers/abstract/america-the-beautiful-230904.jpg",
	passport_validity: "Whatever you want because freedom",
	passport_pages: "Whatever you want because freedom",
	tourist_visa: "Whatever you want because freedom",
	vaccinations: "Whatever you want because freedom",
	entry_currency: "Whatever you want because freedom",
	exit_currency: "Whatever you want because freedom"
)

Country.create(
	name: "Israel",
	official_name: "Israel",
	code: "IL",
	flag: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg",
	passport_validity: "Six months",
	passport_pages: "One page required for entry stamp",
	tourist_visa: "Yes, but you can obtain at the port of entry",
	vaccinations: "Polio vaccination up to 1 year before travel is recommended.",
	entry_currency: "None",
	exit_currency: "None" 
)

######################################
## WARNINGS ##
######################################

warning_page = mechanize.get("http://travel.state.gov/content/passports/english/alertswarnings.html")

table = warning_page.at('table > tbody')

trs = table.css('tr')
links = trs.css('a')

array = []

trs.each do |tr|
	tr.css('td').each do |line|
		array << line.text.strip
	end
end

warning_array = array.each_slice(3).to_a
i = 0
warning_array.each do |warning|
	warning << links[i].attributes["href"].value
	i += 1
end

warning_array.each do |warning|
	search = warning[2].gsub(" Travel Warning", "") if warning[0] == "Warning"
	country = Country.where(name: search).first
	country == nil ? country = 0 : country = country.id
	Warning.create(
		country_id: country,
		warning_type: warning[0],
		date: warning[1],
		location: warning[2],
		warning_link: "http://travel.state.gov#{warning[3]}"
		)
end

######################################
## DESTINATIONS ##
######################################

destinations = [
"bangladesh",
"belgium",
"burkina-faso",
"bulgaria",
"http://www.lonelyplanet.com/bosnia-and-hercegovina/things-to-do/top-things-to-do-in-bosnia-hercegovina",
"brunei-darussalam",
"bolivia",
"japan",
# "burundi",
"benin",
"bhutan",
"jamaica",
"botswana",
"brazil",
"the-bahamas",
"belarus",
"belize",
"russia",
"rwanda",
"serbia",
"lithuania",
"luxembourg",
# "liberia",
"romania",
# "guinea-bissau",
"guatemala",
"greece",
# "guinea",
"http://www.lonelyplanet.com/the-guianas/guyana/things-to-do/top-things-to-do-in-guyana",
"georgia",
"england",
"gabon",
# "guinea",
"the-gambia",
"denmark",
"kuwait",
"ghana",
"oman",
# "somalia",
"kosovo",
"jordan",
"croatia",
"haiti",
"hungary",
"honduras",
"puerto-rico",
# "palestine",
"portugal",
"paraguay",
"panama",
"papua-new-guinea",
"peru",
"pakistan",
"http://www.lonelyplanet.com/philippines/things-to-do/top-things-to-do-in-the-philippines",
"poland",
"cyprus",
"zambia",
# "w.-sahara",
"estonia",
"egypt",
"south-africa",
# "ecuador",
"albania",
# "angola",
"kazakhstan",
"ethiopia",
"zimbabwe",
"spain",
"eritrea",
"montenegro",
"moldova",
"madagascar",
"morocco",
"uzbekistan",
"http://www.lonelyplanet.com/myanmar-burma/things-to-do/top-things-to-do-in-myanmar",
# "mali",
"mongolia",
"macedonia",
"malawi",
# "mauritania",
# "uganda",
"malaysia",
"mexico",
"vanuatu",
"france",
"finland",
"fiji",
# "england",
"nicaragua",
"the-netherlands",
"norway",
"namibia",
"new-caledonia",
"niger",
"nigeria",
"new-zealand",
"nepal",
"http://www.lonelyplanet.com/cote-divoire/things-to-do/top-things-to-do-in-cote-d-ivoire",
"switzerland",
"colombia",
"china",
"cameroon",
"chile",
"canada",
"http://www.lonelyplanet.com/congo/things-to-do/top-things-to-do-in-the-republic-of-congo",
# "central-african-republic",
"http://www.lonelyplanet.com/congo/things-to-do/top-things-to-do-in-the-republic-of-congo",
"http://www.lonelyplanet.com/czech-republic/things-to-do/top-things-to-do-in-the-czech-republic",
"cyprus",
"costa-rica",
"cuba",
"swaziland",
# "syria",
"kyrgyzstan",
# "kenya",
"sudan",
"http://www.lonelyplanet.com/the-guianas/suriname/things-to-do/top-things-to-do-in-suriname",
"cambodia",
"el-salvador",
# "slovakia",
"south-korea",
"slovenia",
# "korea-north",
# "somalia",
"senegal",
"sierra-leone",
"http://www.lonelyplanet.com/solomon-islands/things-to-do/top-things-to-do-in-solomon-islands",
"saudi-arabia",
"sweden",
"sudan",
# "http://www.lonelyplanet.com/dominican-republic/things-to-do/top-things-to-do-in-the-dominican-republic",
"djibouti",
"denmark",
"germany",
"yemen",
"austria",
"algeria",
"http://www.lonelyplanet.com/usa/things-to-do/top-things-to-do-in-the-usa",
"latvia",
"uruguay",
"lebanon",
"laos",
"taiwan",
# "http://www.lonelyplanet.com/trinidad-and-tobago/things-to-do/top-things-to-do-in-trinidad-tobago",
"turkey",
"sri-lanka",
"tunisia",
"east-timor",
"turkmenistan",
"tajikistan",
"lesotho",
"thailand",
# "antarctica",
"togo",
# "chad",
"libya",
"united-arab-emirates",
"venezuela",
"afghanistan",
# "iraq",
"iceland",
# "iran",
"armenia",
"italy",
"vietnam",
"argentina",
"australia",
# "israel",
"india",
"tanzania",
"azerbaijan",
"ireland",
"indonesia",
"ukraine",
"qatar",
"mozambique"]

destinations.each do |country|
	country.length > 50 ? url = country : url = "http://www.lonelyplanet.com/#{country}/things-to-do/top-things-to-do-in-#{country}"
	page = mechanize.get(url)
	thing = page.at('.stack__content')
	places = thing.css('.card__mask')
	places.each do |place|
	countries.key(country) == nil ? id = nil : id = Country.where(name: country.capitalize).first.id if Country.where(name: country.capitalize).first != nil
		Destination.create(
			country_id: id,
			name: place.css('.card__content__title').children.text.lstrip.chomp,
			desc: place.css('.card__content__desc').children[1].children.text.lstrip.chomp
		)
	end
end

